### ISSUE TITLE
[Feat] 1주차 과제

### ISSUE THREAD

**Issue by minnnidev** [31st-IN-SOPT-iOS-Part/MIN#1]
### 🍎 이슈 요약
오토레이아웃 이용하여 카카오톡 앱 클론

### 🍏 ToDo
- [x] 오토레이아웃 이용하여 1주차 과제 수정
- [x] 화면 전환 추가 
- [x] 데이터 전달 추가
