### ISSUE TITLE
SwiftUI 컴포넌트 이해

### ISSUE THREAD

**Issue by minnnidev** [31st-IN-SOPT-iOS-Part/MIN#5]
### 🍎 이슈 요약
인프런 한 조각씩 배우는 SwiftUI - 입문편의 SwiftUI 컴포넌트 배우기

### 🍏 ToDo
- [ ] 눌러서 쓰는 Button 사용해 보기
- [ ] 글자를 보여주는 Text 사용해 보기
- [ ] Image 추가해 보기
- [ ] Stack 이용해 보기
- [ ] ScrollView 사용해 보기
- [ ] List 사용해 보기
- [ ] Section 이해
- [ ] 컴포넌트 사이의 공간을 만들어주는 Spacer
- [ ] Color
