### ISSUE TITLE
[Feat] 3차 과제

### ISSUE THREAD

**Issue by minnnidev** [31st-IN-SOPT-iOS-Part/MIN#6]
### 🍎 이슈 요약
3차 세미나 과제

### 🍏 ToDo
- [x] tab bar 구현
- [x] 친구 TableView 구현
- [x] 채팅 CollectionView 구현 -> 배너 디테일 수정 필요
- [x] 사진 CollectionView 구현 -> 사진 선택 시 번호 표현 수정 필요
- [x] 생각 과제
- [x] 심화 과제
